### PR TITLE
Add max_participants = 4 in activity.info

### PR DESCRIPTION
**Pull request by AbrahmAB**
Without this property max_participant user cannot invite other users to join a shared activity
    if condition in jarabe.view.buddymenu.py #L186 is not satisfied wihout this property
    link --> https://goo.gl/SoqYZW

### CODE REVIEW

**Comment by AbrahmAB** [comment]
self._max_participants is initialized to 0 in sugar3/bundle/activitybundle.py
If the filed is missing then max_participants will remain zero!

**Comment by walterbender** [comment]
/me needs to investigate. As I recall, we were ignoring max_participants if it was not set in the activity for backward compatibility.

**Comment by walterbender** [comment]
Here is what I have observed:

If there is no max_participants set in activity.info, then the default of 0 is returned
In meshbox, the test for shareable is max_participants is 0 or current_participants < max_participants.

So the problem you are experiencing must have its roots elsewhere.

Still, I am OK to set the limit to 4 for Physics (not 100).

**Comment by AbrahmAB** [comment]
Forced push with `max_participants = 4`
This will fix the problem for now. Later the root cause can be investigated.

**Pull request merged**
