### PR TITLE
fixes TypeError %X format and keyError-'saveid'

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
TypeError: %X format: an integer is required, not float
Reproduction - Start physics -> click on Toggle random color button to turn it off -> try drawing something
@quozl @chimosky please review.

### CODE REVIEW

**Comment by Saumya-Mishra9129** [comment]
783d080 fixes #33.

**Comment by chimosky** [comment]
Reviewed, thanks.

Can you explain why your solution in 783d080 works? 
As following the steps in #33  without your solution, the error doesn't persist.

**Comment by Saumya-Mishra9129** [comment]
> Reviewed, thanks.
> 
> Can you explain why your solution in [783d080](https://github.com/sugarlabs/physics/commit/783d08032fbff185b3ebcce34988e81be732405e) works?
> As following the steps in #33 without your solution, the error doesn't persist.
> 
> @quozl, the example selected are supposed to be displayed right as nothing happens when I select an example.

The error can be reproduced by making a circle , adding motor and let click on stop button to stop rotation of circle. You can look at issue #27 .

**Comment by quozl** [comment]
Thanks for noticing that https://github.com/sugarlabs/physics/issues/27 and https://github.com/sugarlabs/physics/issues/33 have the same traceback.

Tested, does fix #33, does fix the traceback of #27, but not the other symptoms there.

Merged with commit message rewrite to include tracebacks.  Please use "Fix" instead of "Fixed", see _imperative mood_ in [Making Commits](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).  It makes way more sense when reading commit history during problem analysis, and is shorter.

**Pull request closed without merging**
