### PR TITLE
Reduce maximum restitution

### LINKED ISSUE #28: Bouncy objects bounce higher and higher
* right-click on the circle or triangle tool button,
* select all three characteristics to the left (feather, basketball, skates),
* click and drag half way up the canvas to create the object. and for a triangle make the base horizontal,
* try different sizes.

The object will fall and bounce, and will not gain any rotational momentum.

Some objects eventually stop moving.

Large objects bounce higher and higher each time.

### PR DESCRIPTION
**Pull request by sparshg**
Refer: https://github.com/sugarlabs/physics/issues/28#issuecomment-1644697676
@chimosky I have set the restitution to 0.95 instead of 1 to atleast prevent the system from gaining energy and becoming unstable.

### CODE REVIEW

**Comment by sparshg** [comment]
@quozl Can you take a look at this? Thanks

**Comment by quozl** [comment]
What specifically do you need?  I raised the issue because I didn't plan to fix it myself; otherwise I would have fixed it immediately when the code was in my head.

Various resources give the bounce height of a basketball in competition at standard inflation, temperature, and air pressure, of between 60% and 80%.  16% doesn't seem right, nor does 93%.  100% is not realistic simulation.

**Comment by sparshg** [comment]
I did set it to 95% because it was close to the original value of 100%, but yes it won't be realistic. I think 70% would be a good choice then and solve all the issues too.

**Comment by chimosky** [comment]
Tested 53d9541, 70% is a good choice.

**Pull request merged**
